name: deployment
on:
  deployment:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: LOG
        run: echo PAYLOAD="${{ github.event.deployment.payload }}"

      - name: checkout_repository
        uses: actions/checkout@v3
      
      - name: HELM TEMPLATE
        run: helm template hello-world
        working-directory: charts
  